### ISSUE TITLE
Latest release not running

### ISSUE THREAD

**Issue by ShufflePerson** [jwebmeister/tacspeak#18]
python --version
`Python 3.11.0`

Full log:
```
tacspeak.exe
Tacspeak version 0.1.5

    Tacspeak - speech recognition for gaming
    © Copyright 2023 by Joshua Webb

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

engine (INFO): Initialized 'kaldi' SR engine: KaldiEngine().
engine (INFO): Loading Kaldi-Active-Grammar v3.1.0 in process 21472.
engine (INFO): Kaldi options: {'model_dir': None, 'tmp_dir': None, 'audio_input_device': None, 'audio_self_threaded': True, 'audio_auto_reconnect': True, 'audio_reconnect_callback': None, 'retain_dir': None, 'retain_audio': False, 'retain_metadata': False, 'retain_approval_func': None, 'vad_aggressiveness': 3, 'vad_padding_start_ms': 150, 'vad_padding_end_ms': 250, 'vad_complex_padding_end_ms': 600, 'auto_add_to_user_lexicon': False, 'allow_online_pronunciations': False, 'lazy_compilation': True, 'invalidate_cache': False, 'expected_error_rate_threshold': None, 'alternative_dictation': None, 'compiler_init_config': {}, 'decoder_init_config': {}, 'listen_key': 5, 'listen_key_toggle': -1}
kaldi.model (WARNING): <kaldi_active_grammar.model.Model object at 0x0000019553D38290>: creating tmp dir: 'kaldi_model\\cache.tmp\\'
kaldi.model (WARNING): model_dir has no version information; errors below may indicate an incompatible model
Traceback (most recent call last):
  File "C:\dev\tacspeak\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\dev\tacspeak\.venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "cli.py", line 59, in <module>
  File "cli.py", line 36, in main
  File "C:\dev\tacspeak\tacspeak\__main__.py", line 115, in main
  File "C:\dev\tacspeak\.venv\Lib\site-packages\dragonfly\engines\backend_kaldi\engine.py", line 196, in connect
  File "C:\dev\tacspeak\.venv\Lib\site-packages\dragonfly\engines\backend_kaldi\compiler.py", line 71, in __init__
  File "C:\dev\tacspeak\.venv\Lib\site-packages\kaldi_active_grammar\compiler.py", line 266, in __init__
  File "C:\dev\tacspeak\.venv\Lib\site-packages\kaldi_active_grammar\model.py", line 212, in __init__
  File "C:\dev\tacspeak\.venv\Lib\site-packages\kaldi_active_grammar\model.py", line 325, in create_missing_files
  File "C:\dev\tacspeak\.venv\Lib\site-packages\kaldi_active_grammar\model.py", line 323, in check_file
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by ShufflePerson** [comment]
I didn't download the model. My bad
