### ISSUE TITLE
'KeyStateGetter' from 'dragonfly.actions' missing.

### ISSUE THREAD

**Issue by TL044CN** [jwebmeister/tacspeak#31]
Not running (should not matter that its linux because all the python libs exist here too)
Reproduction:
1. Fresh out of the box (from git) clone of Tacspeak. (git clone ...)
2. python -m venv ./.venv
3. pip install -r requirements.txt
4. dolphin .& `(this is what windows calls "Explorer") (. is this directory, & is run in parallel) to copy the kaldi_model in`
5. python ./cli.py
6. See this:
```
(.venv)  python ./cli.py                                                                                                                              (base) 
Tacspeak version 0.2.0

    Tacspeak - speech recognition for gaming
    © Copyright 2023-2024 by Joshua Webb

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
        
engine.kaldi (WARNING): Failed to import from Kaldi engine module: cannot import name 'KeyStateGetter' from 'dragonfly.actions' (/mnt/sto1/Program Files/tacspeak/tacspeak/.venv/lib/python3.11/site-packages/dragonfly/actions/__init__.py)
Traceback (most recent call last):
  File "/mnt/sto1/Program Files/tacspeak/tacspeak/./cli.py", line 140, in <module>
    main()
  File "/mnt/sto1/Program Files/tacspeak/tacspeak/./cli.py", line 116, in main
    tacspeak_main()
  File "/mnt/sto1/Program Files/tacspeak/tacspeak/tacspeak/__main__.py", line 112, in main
    engine = get_engine('kaldi',**KALDI_ENGINE_SETTINGS)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sto1/Program Files/tacspeak/tacspeak/.venv/lib/python3.11/site-packages/dragonfly/engines/__init__.py", line 197, in get_engine
    raise EngineError("Requested engine %r not available."
dragonfly.engines.base.engine.EngineError: Requested engine 'kaldi' not available.
```

I suspect some kind of update of dragonfly, removing the `KeyStateGetter` from its `__init__.py`? dunno im a c++ dev, dont know python.

**Comment by jwebmeister** [comment]
Linux isn't currently supported. Tacspeak uses a modified version of dragonfly. See this issue for more details https://github.com/jwebmeister/dragonfly/issues/4

**Comment by JustCauseWhyNot** [comment]
Linux currently isn't supported correct?
